namespace: lordoftheflies
name: freeipa_collection
version: 0.0.2
description: Collection of roles which needed for internal-policy-audit.
authors:
  - Thomas Woerner <twoerner@redhat.com>
  - László Hegedűs <laszlo.hegedus@cherubits.hu>

repository: https://github.com/lordoftheflies/freeipa_collection
documentation: https://github.com/lordoftheflies/freeipa_collection/blob/master/README.md
homepage: https://github.com/lordoftheflies/freeipa_collection
issues: https://github.com/lordoftheflies/freeipa_collection/issues

readme: README.md
license: GPL-3.0-or-later
license_file: COPYING

dependencies:

tags:
  - cherubits
  - identity
  - ipa
  - freeipa
  - cluster
  - collection
