namespace: "lordoftheflies"
name: "ansible_collection_freeipa"
version: "0.0.1"
description: "Collection of roles which needed for internal-policy-audit."

authors:
  - "Thomas Woerner <twoerner@redhat.com>"
  - "László Hegedűs <laszlo.hegedus@cherubits.hu>"

repository: "https://github.com/lordoftheflies/ansible-collection-freeipa"
documentation: "https://github.com/lordoftheflies/ansible-collection-freeipa/blob/master/README.md"
homepage: "https://github.com/lordoftheflies/ansible-collection-freeipa"
issues: "https://github.com/lordoftheflies/ansible-collection-freeipa/issues"

dependencies: {}

readme: "README.md"
license: "GPL-3.0-or-later"
license_file: "COPYING"

tags:
  - "cherubits"
  - "identity"
  - "ipa"
  - "freeipa"
  - "cluster"
  - "collection"
